In [1]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0,x_test/255.0

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6726547 ,  1.1713212 , -1.1921197 , -0.32681027, -0.1935316 ,
        -0.4118807 , -0.2911097 , -0.94063437,  0.49453712, -1.1216584 ]],
      dtype=float32)

In [9]:
x_train[:1]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.05457644, 0.34501162, 0.03246417, 0.07712648, 0.08812227,
        0.07083663, 0.07992968, 0.04174679, 0.17535177, 0.03483415]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1],predictions).numpy()

2.647379

In [14]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3020 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1424 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 2s 814us/step - loss: 0.1076 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 1s 768us/step - loss: 0.0896 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 2s 804us/step - loss: 0.0759 - accuracy: 0.9761


In [16]:
model.evaluate(x_test, y_test, verbose = 2)

313/313 - 0s - loss: 0.0756 - accuracy: 0.9767


[0.07561247050762177, 0.9767000079154968]

In [17]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [19]:
# Getting the probability for first 5 samples.
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.94990400e-07, 8.72323380e-10, 9.57082307e-07, 4.67049176e-05,
        6.40178622e-12, 2.77508025e-08, 4.32922014e-12, 9.99851704e-01,
        1.52695662e-07, 1.00075398e-04],
       [7.60797292e-09, 6.24739041e-05, 9.99896765e-01, 3.55461489e-05,
        2.49893989e-15, 4.17365044e-07, 9.29972810e-09, 1.51086088e-11,
        4.74143962e-06, 1.47096460e-13],
       [6.28328280e-07, 9.98130500e-01, 4.75817971e-04, 1.89754555e-05,
        2.87824187e-05, 1.74761340e-06, 2.53942926e-05, 9.76203824e-04,
        3.41660692e-04, 1.73994934e-07],
       [9.99969602e-01, 5.71621778e-11, 5.29490035e-06, 5.12404128e-08,
        2.10705068e-07, 6.66593820e-08, 3.57282079e-06, 2.16925628e-06,
        1.45389336e-07, 1.88802405e-05],
       [1.67505041e-05, 4.19225499e-09, 6.09922745e-06, 9.11699729e-08,
        9.87716973e-01, 3.13403952e-08, 6.90992920e-07, 1.75646361e-04,
        1.12333865e-07, 1.20835910e-02]], dtype=float32)>